college-canteen-order-master/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    #path('signup/', views.SignUp.as_view(), name="signup"),
]

college-canteen-order-master/canteen/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.SignUp.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('products/',include("products.urls", namespace="products")),
]

from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

college-canteen-order-master/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('',views.MultipleProducts, name='all'),
    path('details/<int:id>',views.SingleProduct,name='details'),
    #path('addCart/<int:id>',views.addToCart,name='addToCart'),
    # path('checkout/',views.CheckoutView.as_view(), name='checkout'),
    path('order-summary/',views.OrderSummaryView.as_view(), name='summary'),
    path('add-to-cart/<slug:slug>/',views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug:slug>/',views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug:slug>/',views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/',views.PlaceOrder.as_view(), name='checkout'),
    path('manage-orders/',views.OrderList.as_view(),name='manage-orders'),
    path('order-ready/<username>/<int:id>/',views.OrderReady.as_view(),name='order-ready'),
    path('order-cancelled/<username>/<int:id>/',views.OrderCancelled.as_view(),name='order-cancelled'),
    path('order-collected/<username>/<int:id>/',views.OrderCollected.as_view(),name='order-collected'),
]

college-canteen-order-master/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CollegeDine</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>


<link rel="stylesheet" href="{% static 'css/master.css' %}">

  </head>
  <body>

    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">CollegeDine</a>
        </div>

            <div class="dropdown">
  <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Menu
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">All</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Indian</a>
    <a class="dropdown-item" href="#">Chinese</a>
    <a class="dropdown-item" href="#">Continental</a>
    <a class="dropdown-item" href="#">Beverages</a>
  </div>
</div>

        <div class="navbar-nav ml-auto">
          {% if user.is_superuser %}
          <a class="nav-item nav-link" href="{% url 'products:manage-orders' %}" class="btn btn-simple">Manage Orders</a>
          {% endif %}
          {% if user.is_authenticated %}
           <a class="nav-item nav-link" href="{% url 'products:summary' %}"><i class="fa fa-shopping-cart"><p class="inlinewithicon"> Cart</p></i></a>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a>
          {% else %}

            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
            <a class="nav-item nav-link" href="{% url 'home' %}" class="btn btn-simple">Sign up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="mt-5 pt-4 messages">
 {% if messages %}
     {% for message in messages %}
     <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
       {{ message }}
       <button type="button" class="close" data-dismiss="alert" aria-label="Close">
         <span aria-hidden="true">&times;</span>
       </button>
     </div>
     {% endfor %}
 {% endif %}
 </div>
    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

    <script src="{% static "canteen/js/master.js"%}" type="text/javascript" ></script>

    <!-- Latest compiled and minified jQuery -->
    <!-- Latest compiled and minified JavaScript -->
<script src="https://unpkg.com/popper.js@1.15.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
  <script>
  $(() => {

    $('.dropdown-menu a').click(function(){

      var cat = $(this).text();


      if(cat === "Indian") {
        window.location.href = "/products/?cat=I"
      } else if(cat === "Chinese") {
        window.location.href = "/products/?cat=CH"
      } else if(cat === "Continental") {
        window.location.href = "/products/?cat=CN"
      } else if(cat === "Beverages") {
        window.location.href = "/products/?cat=BV"
      } else  {
        window.location.href = "/products/?cat=all"
      }

    });



  });
  </script>
</html>

college-canteen-order-master/templates/index.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}



{% if user.is_authenticated %}
<div class="siteinfodiv">
<div class="infoheader">
  <h1>CollegeDine: A website for the college canteen</h1>
</div>
  <h3>Our college has a lot of students, and correspondingly a lot of rush in the canteen. As a result, many of the students are left waiting to recieve their orders for a major part of the break, leaving them with no time to complete it.</h3>
<!-- <img src="https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjKyr2b4q3lAhUYaI8KHZo-CvUQjRx6BAgBEAQ&url=%2Furl%3Fsa%3Di%26source%3Dimages%26cd%3D%26ved%3D%26url%3Dhttps%253A%252F%252Fwww.bbcgoodfood.com%252Fhowto%252Fguide%252Fbalanced-diet-vegan%26psig%3DAOvVaw1SiPq45prcviqvHDHsZYZn%26ust%3D1571761537304462&psig=AOvVaw1SiPq45prcviqvHDHsZYZn&ust=1571761537304462" alt="Image not found"> -->
  <h3>With our website, you can order your food in advance, thus saving the time to come down to the canteen and placing your order. Two emails are sent to your registered Email ID; one when you place your order, and another when it is prepared and ready to be collected.</h3>
  
</div>



{% else %}
<!-- <div id="carouselExampleControls" class="carousel slide carouselwithform" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="">
        hello
      </div>
    </div>
    <div class="carousel-item">
<h1>ejfojern</h1>
    </div>
    <div class="carousel-item">
<h1>oj oj</h1>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> -->

<div class="divwithform" id="divwithform">
    <h1 class="paraone">Welcome to CollegeDine!</h1>

<h2 class="pararemaining">It's a website designed to bring convenience for you.</h2>

<h2 class="pararemaining">We will help you to save time, something which is essential for a college student.</h2>

<h2 class="pararemaining">Sign up to find out how.</h2>
</div>

<div class="signupform" id='signupform'>
  <div class="container h-75">
    <h1>Sign Up</h1>
    <form method="POST" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">Sign Up</button>
      {% endbuttons %}
    </form>
  </div>
</div>

{% endif %}
{% endblock %}

<script>
$("#signupform").height($("#divwithform").height());
</script>

college-canteen-order-master/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}