college-canteen-order-master/canteen/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.SignUp.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('products/',include("products.urls", namespace="products")),
]

from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

college-canteen-order-master/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('',views.MultipleProducts, name='all'),
    path('details/<int:id>',views.SingleProduct,name='details'),
    #path('addCart/<int:id>',views.addToCart,name='addToCart'),
    # path('checkout/',views.CheckoutView.as_view(), name='checkout'),
    path('order-summary/',views.OrderSummaryView.as_view(), name='summary'),
    path('add-to-cart/<slug:slug>/',views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug:slug>/',views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug:slug>/',views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/',views.PlaceOrder.as_view(), name='checkout'),
    path('manage-orders/',views.OrderList.as_view(),name='manage-orders'),
    path('order-ready/<username>/<int:id>/',views.OrderReady.as_view(),name='order-ready'),
    path('order-cancelled/<username>/<int:id>/',views.OrderCancelled.as_view(),name='order-cancelled'),
    path('order-collected/<username>/<int:id>/',views.OrderCollected.as_view(),name='order-collected'),
]

college-canteen-order-master/products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product,Order,OrderItem
from django.views import generic
from django.contrib.auth.decorators import login_required
#from accounts.models import User
from django.contrib.auth.models import User
from django import template
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django.core.mail import send_mail
from .models import Order
from braces.views import SuperuserRequiredMixin
register = template.Library()
# Create your views here.

# class SingleProduct(generic.DetailView):
#     template_name = 'products/product_list.html'
#     model = Product
def SingleProduct(request,id):

    template_name = 'products/product_detail.html'
    context ={'product': Product.objects.get(id=id)}
    if(context is None):
        return #404
    return render(request,template_name,context)

def MultipleProducts(request):
    template_name = 'products/product_list.html'

    cat = request.GET.get('cat', 'all') #All means all categpries of food
    if cat == "all":
        context = {'products':Product.objects.all()}
    elif cat == "I":
        print("RAN")
        context = {'products':Product.objects.filter(category=Product.indian)}
    elif cat == "CN":
        context = {'products':Product.objects.filter(category=Product.continental)}
    elif cat == "BV":
        context = {'products':Product.objects.filter(category=Product.beverages)}
    elif cat == "CH":
        context = {'products':Product.objects.filter(category=Product.chinese)}
    else:
        context = {'products':Product.objects.all()}
    return render(request, template_name, context)



# @login_required
# def addToCart(request,id):
#     if request.user.is_authenticated:
#         product = Product.objects.get(id=id)
#
#         user = User.objects.get(username=request.user.username)
#         try:
#             current_cart = Order.objects.get(user=user,in_cart=True)
#         except:
#             current_cart = Order(user=user,in_cart=True)
#             current_cart.save()
#
#         order_item = OrderItem(order_id=current_cart,product=product,quantity=1)
#         order_item.save()
#         return MultipleProducts(request)

# class CheckoutView(generic.View):
#     def get(self, *args, **kwargs):
#         try:
#             order = Order.objects.get(user=self.request.user, ordered=False)
#             context = {
#                 'order': order,
#             }
#             return render(self.request, "checkout.html", context)
#         except ObjectDoesNotExist:
#             messages.info(self.request, "You do not have an active order")
#             return redirect("products:checkout")
#
#     def post(self, *args, **kwargs):
#         try:
#             order = Order.objects.get(user=self.request.user, ordered=False)
#             return redirect("products:checkout")
#         except ObjectDoesNotExist:
#             messages.warning(self.request, "You do not have an active order")
#             return redirect("products:summary")


class PlaceOrder(LoginRequiredMixin,generic.View):
    def get(self,*args,**kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered = False)
            items = order.items
            total = order.get_total()
            message = "Thanks for placing an order (Order ID-{}). Please pay ₹{} when collecting the order. An e-mail will be sent to you when your food is ready.".format(order.id,total)
            subject = "Order Confirmation"
            emailFrom = settings.EMAIL_HOST_USER
            emailTo = [self.request.user.email]
            send_mail(subject, message, emailFrom, emailTo, fail_silently=False,)
            order.ordered = True
            order.save()
            context={'success':messages.success(self.request,'Order successfully placed! An email has been sent to you on your registered Email ID.')}
            return render(self.request,'index.html',context)
        except ObjectDoesNotExist:
            messages.warning(self.request,"You do not have an existing order")


class OrderList(SuperuserRequiredMixin,generic.ListView):
    #permission_required = ('user.is_superuser')
    template_name = 'products/allorders.html'
    model = Order

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['pendingorders'] = Order.objects.filter(ordered=True,being_delivered=False,received=False)
        context['preparedorders'] = Order.objects.filter(ordered=True,being_delivered=True,is_cancelled=False,received=False)
        return context

class OrderReady(SuperuserRequiredMixin,generic.View):
    def get(self,*args,**kwargs):
        try:
            order = Order.objects.get(user__username__iexact=self.kwargs.get("username"),id=self.kwargs.get("id"),ordered=True,being_delivered=False,is_cancelled=False,received=False)
        #             return queryset.filter(
        #     user__username__iexact=self.kwargs.get("username")
        # )  #### bug
            # username = order.user.username
            total = order.get_total()
            message = "Your order (Order ID-{}) is ready for you. Please pay ₹{} when collecting the order. Thank you for purchasing from CollegeDine.".format(order.id,total)
            subject = "Order Ready"
            emailFrom = settings.EMAIL_HOST_USER
            emailTo = [order.user.email]
            send_mail(subject, message, emailFrom, emailTo, fail_silently=False,)
            order.being_delivered = True
            order.save()
            return redirect('products:manage-orders')
            #return render(self.request,'products/allorders.html',{})
        except ObjectDoesNotExist:
            messages.warning(self.request,"This order does not exist.")


class OrderCancelled(SuperuserRequiredMixin,generic.View):
    def get(self,*args,**kwargs):
        try:
            order = Order.objects.get(user__username__iexact=self.kwargs.get("username"),id=self.kwargs.get("id"),ordered=True,being_delivered=False,is_cancelled=False,received=False)
            total = order.get_total()
            message = "Your order (Order ID-{}) could not be completed. We sincerely apologise for the inconvenience caused.".format(order.id)
            subject = "Order Cancelled"
            emailFrom = settings.EMAIL_HOST_USER
            emailTo = [order.user.email]
            send_mail(subject, message, emailFrom, emailTo, fail_silently=False,)
            order.being_delivered = True
            order.is_cancelled = True
            order.save()
            return redirect('products:manage-orders')
            #return render(self.request,'products/allorders.html',{})
        except ObjectDoesNotExist:
            messages.warning(self.request,"This order does not exist.")


class OrderCollected(SuperuserRequiredMixin,generic.View):
    def get(self,*args,**kwargs):
        try:
            order = Order.objects.get(user__username__iexact=self.kwargs.get("username"),id=self.kwargs.get("id"),ordered=True,being_delivered=True,is_cancelled=False,received=False)
            total = order.get_total()
            order.received = True
            order.save()
            return redirect('products:manage-orders')
            #return render(self.request,'products/allorders.html',{})
        except ObjectDoesNotExist:
            messages.warning(self.request,"This order does not exist.")


class OrderSummaryView(LoginRequiredMixin,generic.View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order ###CHECK AGAIN
            }
            return render(self.request,'products/order_summary.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order. Head on over to our menu to select from a delicious variety of items!")
            return redirect("/") ##check url


#for all following functions check if slug can replace id
@login_required
def add_to_cart(request,slug):
    product = get_object_or_404(Product,slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        product=product,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(product__slug=product.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item quantity was updated.")
            return redirect("products:summary")
        else:
            order.items.add(order_item)
            messages.info(request, "This item was added to your cart.")
            return redirect("products:summary")
    else:
        order = Order.objects.create(user=request.user)
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
        return redirect("products:summary")


@login_required
def remove_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(product__slug=product.slug).exists():
            order_item = OrderItem.objects.filter(
                product=product,
                user=request.user,

college-canteen-order-master/products/templates/products/allorders.html
{% extends 'products/product_base.html' %}
{% block preproduct %}
<div class="container headerdiv">
    <h3 class="headertext">Pending Orders:</h3>
</div>
{% endblock %}
{% block product_content %}

    <div class="container jumbotron">

    <div class="table-responsive text-nowrap">

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">User</th>
            <th scope="col" colspan="2">Items</th>
            <th scope="col" colspan="2">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for order in pendingorders %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order.user.username }}</td>
            <td colspan="2">
            {% for item in order.items.all %}
            <h6>{{ item }}</h6>
            {% endfor %}
          </td>
            <td>
              <a class='btn btn-primary' href="{% url 'products:order-ready' username=order.user.username id=order.id %}">Order Ready</a>
            </td>
            <td>
              <a class="btn btn-danger" href="{% url 'products:order-cancelled' username=order.user.username id=order.id %}">Reject Order</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>No pending orders</td>
        </tr>
        {% endfor %}

        </tbody>
    </table>

    </div>

    </div>

    <div class="container headerdiv preparedorderdiv">
        <h3 class="headertext">Prepared Orders:</h3>
    </div>

    <div class="container jumbotron">

    <div class="table-responsive text-nowrap">

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">User</th>
            <th scope="col" colspan="2">Items</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for order in preparedorders %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order.user.username }}</td>
            <td colspan="2">
            {% for item in order.items.all %}
            <h6>{{ item }}</h6>
            {% endfor %}
          </td>
            <td>
              <a class='btn btn-success' href="{% url 'products:order-collected' username=order.user.username id=order.id %}">Order Collected</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>No pending orders</td>
        </tr>
        {% endfor %}

        </tbody>
    </table>

    </div>

    </div>

{% endblock %}

college-canteen-order-master/products/templates/products/order_summary.html
{% extends 'products/product_base.html' %}
{% block content %}
  <div class="container jumbotron">

  <div class="table-responsive text-nowrap">
  <h2>Order Summary</h2>
  <table class="table">
      <thead>
      <tr>
          <th scope="col">#</th>
          <th scope="col">Item title</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total Item Price</th>
      </tr>
      </thead>
      <tbody>
      {% for order_item in object.items.all %}
      <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ order_item.product.name }}</td>
          <td>{{ order_item.product.price }}</td>
          <td>
            <a href="{% url 'products:remove-single-item-from-cart' order_item.product.slug %}"><i class="fa fa-caret-down" aria-hidden="true"></i></a>
              {{ order_item.quantity }}
              <a href="{% url 'products:add-to-cart' order_item.product.slug %}"><i class="fa fa-caret-up" aria-hidden="true"></i></a>
          </td>
          <td>

              ₹{{ order_item.get_total_item_price }}

          <a style='color: red;' href="{% url 'products:remove-from-cart' order_item.product.slug %}">
              <i class="fa fa-trash trashicon" aria-hidden="true"></i>
          </a>
          </td>
      </tr>
      {% empty %}
      <tr>
          <td colspan='5'>Your cart is empty</td>
      </tr>
      <tr>
          <td colspan="5">
          <a class='btn btn-primary float-right' href="{% url 'products:all' %}">Continue shopping</a>
          </td>
      </tr>
      {% endfor %}

      {% if object.get_total %}
      <tr>
          <td colspan="4"><b>Order Total</b></td>
          <td><b>₹{{ object.get_total }}</b></td>
      </tr>

      <tr>
          <td colspan="5">
          <a class='btn btn-warning float-right ml-2 checkoutbutton' href="{% url 'products:checkout' %}">Proceed to checkout</a>
          <a class='btn btn-primary float-right continueshoppingbutton' href="{% url 'products:all' %}">Continue shopping</a>
          </td>
      </tr>
      {% endif %}
      </tbody>
  </table>

  </div>

  </div>

{% endblock %}

college-canteen-order-master/products/templates/products/product_base.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    {% block preproduct %}{% endblock %}
    {% block product_content %}{% endblock %}

  </div>

</div>

{% endblock %}

college-canteen-order-master/products/templates/products/product_detail.html
{% extends 'products/product_base.html' %}

{% block content %}
Product details
{% endblock %}

college-canteen-order-master/products/templates/products/product_list.html
{% extends 'products/product_base.html' %}
{% block preproduct %}

{% endblock %}
{% block product_content %}

<div>
  <div class="container">
  <div class="row">

      {% for i in products %}
      <div class="col-lg-4 d-flex align-items-stretch">
        <div class="card cardmodify cardbackground" style="width: 18rem;">
          <div class="card-header">
            <h5><b>{{ i.name }}</b></h5>
          </div>
          <img class="card-img-top" src="{{ i.image.url }}" alt="Card image cap">
          <div class="card-body d-flex flex-column" data-cat="{{ i.category }}">
            <p class="card-text">{{ i.description }}</p>
<div class="mt-auto">
  <p class="card-text">Preparation time: {{ i.prep_time }} mins</p>
    <p class="card-text">Price: ₹{{ i.price }}</p>
<div class="align-self-end container">
  <a href="{{ i.get_add_to_cart_url }}" class="btn btn-success btn-sm addtocartbutton">Add to cart</a>
<a href="{{ i.get_remove_from_cart_url }}" class="btn btn-danger btn-sm removefromcartbutton">Remove from cart</a>
</div>

</div>


          </div>
        </div>
</div>
      {% endfor %}

  </div>



{% endblock %}